version: '3'
services:
    php-apache:
        image: php:7.4.28-apache-buster
        ports:
            - 80:80
        links:
            - 'mariadb'

    mariadb:
        image: mariadb:10.7.3
        environment:
            TZ: "Europe/Minsk"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'testpassword'
            MYSQL_DATABASE: 'testdb'


